# Generated by Django 5.2.5 on 2025-08-12 06:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, validators=[django.core.validators.MinLengthValidator(3)])),
                ('platform', models.CharField(choices=[('PC Games', 'PC Games'), ('Console Games', 'Console Games'), ('Other Games', 'Other Games')], default='Other Games', max_length=20)),
                ('release_date', models.DateField()),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('screenshot_url', models.URLField(blank=True)),
                ('player', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='players.player')),
            ],
            options={
                'ordering': ['-level', 'title'],
            },
        ),
    ]
