# Generated by Django 5.2.5 on 2025-08-12 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(error_messages={'unique': 'That nickname is already in use!'}, help_text='*Allowed nicknames contain letters and digits.', max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(60), django.core.validators.RegexValidator(message='Nickname must contain only letters and digits!', regex='^[A-Za-z0-9]+$')])),
                ('email', models.CharField(error_messages={'unique': 'That email is already registered!'}, max_length=60, unique=True)),
                ('achievements', models.TextField(blank=True, help_text='*Share your achievements.', null=True)),
                ('is_pro', models.BooleanField(default=False)),
            ],
        ),
    ]
